### ISSUE TITLE
ENM autoprovisioning

### ISSUE THREAD

**Issue by kolayne2021** [vvsviridov/ecellrest#1]
Добрый день! Вы реализовывали работу с проектами ENM  с помощью питон? Возникают проблемы с загрузкой проекта.
`
def import_project(self, project_path: str):
        url = f"https://{self.enm}/auto-provisioning/v1/projects"
        with open(project_path, 'rb') as file:
            resp = self.post(url, data={'file': file})
        return resp

`
Возвращает: {'httpResponseStatus': 500, 'errorTitle': 'Internal Server Error.', 'errorBody': 'Suggested Solution : Use Log Viewer for more informa
tion.', 'errorDetails': None}

Вызываю контекстным менеджером как у вас , наследую класс от Session

**Comment by vvsviridov** [comment]
@kolayne2021
Добрый день, в основном на питоне. Попробуйте так:
```python
def import_project(self, project_path: str):
    url = f"https://{self.enm}/auto-provisioning/v1/projects"
    self.headers.update({
        'Content-Type': 'multipart/form-data',
    })
    with open(project_path, 'rb') as file:
        resp = self.post(url, files={'file': file})
return resp

**Comment by kolayne2021** [comment]
Что-то всё-равно ту же ошибку возвращает ( вручную при этом грузится без ошибок )...

**Comment by kolayne2021** [comment]
Судя по ошибке он жалуется на хедер:

RROR [com.ericsson.oss.services.ap.core.rest.war.response.exceptionmappers.UnhandledExceptionMapper] (ajp-executor-threads - 2271756) Internal Server Error.: java.io.IOException: RESTEASY005050: Unable to get boundary for multipart#012#011at org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataReader.readFrom(MultipartFormDataReader.java:53) [resteasy-multipart-provider-2.3.23.Final-redhat-1.jar:]#012#011at org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataReader.readFrom(MultipartFormDataReader.java:23) [resteasy-multipart-provider-2.3.23.Final-redhat-1.jar:]#012#011at org.jboss.resteasy.core.interception.MessageBodyReaderContextImpl.proceed(MessageBodyReaderContextImpl.java:106) [resteasy-jaxrs-2.3.23.Final-redhat-1.jar:]#012#011at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:168) [resteasy-jaxrs-2.3.23.Final-redhat-1.jar:]#012#011at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:137) [resteasy-jaxrs-2.3.23.Final-redhat-1.jar:]#012#011at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:160) [resteasy-jaxrs-2.3.23.Final-redhat-1.jar:]#012#011at

Если его убрать: 

com.ericsson.oss.services.ap.core.rest.war.response.exceptionmappers.UnhandledExceptionMapper] (ajp-executor-threads - 2271932) Internal Server Error.: org.codehaus.jackson.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value#012 at [Source:


project_path = os.path.join(os.getcwd(), "project", "unzipped_project", "Base_55_555_MM_99.zip")
Путь такой

**Comment by kolayne2021** [comment]
насколько понимаю, проблема с заголовком.

**Comment by kolayne2021** [comment]
Решил удалением api_session.headers.update({"Content-Type": "application/json"}) при аутентификации. Спасибо за помощь!
